import type { Metadata } from "next";
import Script from "next/script";
import localFont from 'next/font/local'
import { Noto_Emoji } from 'next/font/google'
import "./globals.css";
import {cn} from "lib/utils";
import { ThemeProvider, THEME_INIT_SCRIPT } from "@/shared/model";


const norse = localFont({
  src: [
    { path: '../public/fonts/norse/Norse.otf', weight: '400', style: 'normal' },
    { path: '../public/fonts/norse/Norsebold.otf', weight: '700', style: 'normal' },
  ],
  variable: '--font-norse',
  display: 'swap',
})

const notoEmoji = Noto_Emoji({
  subsets: ['emoji'],
  variable: '--font-noto-emoji',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", norse.className, norse.variable, notoEmoji.variable, "text-xl")}
    >
      <body className="min-h-full flex flex-col">
        <Script
          id="theme-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }}
        />
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
