import type { Metadata } from "next";
import localFont from 'next/font/local'
import { Noto_Emoji } from 'next/font/google'
import "./globals.css";
import {cn} from "lib/utils";


const norse = localFont({
  src: [
    { path: '../public/fonts/norse/Norse.otf', weight: '400', style: 'normal' },
    { path: '../public/fonts/norse/Norsebold.otf', weight: '700', style: 'normal' },
  ],
  variable: '--font-norse',
  display: 'swap',
})

const notoEmoji = Noto_Emoji({
  subsets: ['emoji'],
  variable: '--font-noto-emoji',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "dark", norse.className, norse.variable, notoEmoji.variable, "text-xl")}
    >
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
