import type {Metadata} from 'next';
import localFont from 'next/font/local';
import {Header} from './components/header';
import AosInit from '../lib/AosInit';
import './globals.css';

const norse = localFont({
  src: [
    {
      path: '../../public/font/norse/Norse.otf',
      weight: '400',
      style: 'normal',
    }, {
      path: '../../public/font/norse/Norsebold.otf',
      weight: '700',
      style: 'normal',
    }
  ],
  variable: '--font-norse',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${norse.variable} antialiased text-lg font-bold flex flex-col min-h-dvh`}
      >
        <AosInit />
        <Header />
        <main className="px-20 flex justify-between items-center flex-1">
          {children}
        </main>
        <footer className="flex items-center justify-center w-full h-16">
          <p>Made with ❤️ by Maksym Sokolov</p>
        </footer>
      </body>
    </html>
  );
}
