export interface EmojiOption {
    char: string;
    label: string;
}

export interface EmojiCategory {
    label: string;
    emoji: EmojiOption[];
}

/**
 * The default emoji offered by the toolbar's emoji picker, grouped to match
 * the in-game sign symbol reference the user supplied. Any other emoji can
 * still be pasted into a sign directly — this list only backs the picker's
 * dropdown, not what's allowed in the document.
 *
 * Characters must not carry U+FE0F (the emoji-presentation selector): it makes
 * the browser render the full-color system emoji instead of the monochrome
 * Noto Emoji glyph that matches Valheim's sign style.
 */
export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
    {
        label: 'Food & Farm',
        emoji: [
            { char: '🥩', label: 'Raw meat' },
            { char: '🍗', label: 'Cooked meat' },
            { char: '🐟', label: 'Fish' },
            { char: '🍯', label: 'Honey' },
            { char: '🍄', label: 'Mushroom' },
            { char: '🥕', label: 'Carrot' },
            { char: '🫐', label: 'Blueberries' },
            { char: '🌾', label: 'Barley' },
            { char: '🌲', label: 'Sapling' },
            { char: '🍺', label: 'Mead' },
            { char: '🍲', label: 'Stew' },
            { char: '🥛', label: 'Milk' },
            { char: '🧀', label: 'Cheese' },
            { char: '🍎', label: 'Apple' },
            { char: '🍞', label: 'Bread' },
            { char: '🍖', label: 'Meat on bone' },
            { char: '🥚', label: 'Egg' },
            { char: '🌽', label: 'Corn' },
            { char: '🥔', label: 'Potato' },
            { char: '🥬', label: 'Leafy green' },
            { char: '🍇', label: 'Grapes' },
            { char: '🍓', label: 'Strawberry' },
            { char: '🍒', label: 'Cherries' },
            { char: '🌰', label: 'Chestnut' },
            { char: '🍳', label: 'Frying pan' },
            { char: '🍷', label: 'Wine' },
            { char: '🥣', label: 'Bowl' },
            { char: '🍽', label: 'Plate' },
        ],
    },
    {
        label: 'Gear & War',
        emoji: [
            { char: '⚔', label: 'Swords' },
            { char: '🗡', label: 'Dagger' },
            { char: '🛡', label: 'Shield' },
            { char: '🏹', label: 'Bow' },
            { char: '⛏', label: 'Pickaxe' },
            { char: '🔨', label: 'Hammer' },
            { char: '🪓', label: 'Axe' },
            { char: '🧰', label: 'Toolbox' },
            { char: '👑', label: 'Crown' },
            { char: '💍', label: 'Ring' },
            { char: '🧪', label: 'Potion' },
            { char: '🔥', label: 'Fire' },
            { char: '⚡', label: 'Lightning' },
            { char: '💧', label: 'Water drop' },
            { char: '🔱', label: 'Trident' },
            { char: '🪖', label: 'Helmet' },
            { char: '🥾', label: 'Boot' },
            { char: '🧤', label: 'Gloves' },
            { char: '🧥', label: 'Coat' },
            { char: '🎣', label: 'Fishing rod' },
            { char: '🪚', label: 'Saw' },
            { char: '🔧', label: 'Wrench' },
            { char: '⚒', label: 'Hammer and pick' },
            { char: '🛠', label: 'Hammer and wrench' },
            { char: '🪄', label: 'Staff' },
            { char: '📿', label: 'Amulet' },
            { char: '💣', label: 'Bomb' },
            { char: '🎯', label: 'Target' },
            { char: '🕯', label: 'Candle' },
            { char: '🧲', label: 'Magnet' },
        ],
    },
    {
        label: 'Materials',
        emoji: [
            { char: '🪵', label: 'Wood' },
            { char: '🪨', label: 'Stone' },
            { char: '💰', label: 'Coins' },
            { char: '💎', label: 'Gem' },
            { char: '🧵', label: 'Thread' },
            { char: '🟠', label: 'Amber' },
            { char: '🟫', label: 'Bronze' },
            { char: '🔩', label: 'Iron' },
            { char: '🥇', label: 'Gold medal' },
            { char: '🥈', label: 'Silver medal' },
            { char: '🥉', label: 'Bronze medal' },
            { char: '🪙', label: 'Coin' },
            { char: '🔗', label: 'Chain' },
            { char: '🪶', label: 'Feather' },
            { char: '🦴', label: 'Bone' },
            { char: '🧶', label: 'Yarn' },
            { char: '🪢', label: 'Rope' },
            { char: '🧱', label: 'Brick' },
            { char: '🕸', label: 'Cobweb' },
            { char: '🐚', label: 'Shell' },
            { char: '🧊', label: 'Ice' },
            { char: '🏺', label: 'Vase' },
            { char: '🪡', label: 'Needle' },
            { char: '🔶', label: 'Orange diamond' },
            { char: '🔷', label: 'Blue diamond' },
            { char: '🟤', label: 'Brown circle' },
        ],
    },
    {
        label: 'Beasts',
        emoji: [
            { char: '🦌', label: 'Deer' },
            { char: '🐗', label: 'Boar' },
            { char: '🐴', label: 'Lox' },
            { char: '🐝', label: 'Bee' },
            { char: '🕷', label: 'Spider' },
            { char: '🐍', label: 'Serpent' },
            { char: '🐢', label: 'Turtle' },
            { char: '🐞', label: 'Beetle' },
            { char: '💀', label: 'Skull' },
            { char: '☠', label: 'Skull and crossbones' },
            { char: '🧟', label: 'Draugr' },
            { char: '👹', label: 'Troll' },
            { char: '🐌', label: 'Snail' },
            { char: '🐺', label: 'Wolf' },
            { char: '🐻', label: 'Bear' },
            { char: '🐖', label: 'Pig' },
            { char: '🐑', label: 'Sheep' },
            { char: '🐄', label: 'Cow' },
            { char: '🐐', label: 'Goat' },
            { char: '🐎', label: 'Horse' },
            { char: '🐇', label: 'Rabbit' },
            { char: '🐀', label: 'Rat' },
            { char: '🐕', label: 'Dog' },
            { char: '🐈', label: 'Cat' },
            { char: '🦊', label: 'Fox' },
            { char: '🦬', label: 'Bison' },
            { char: '🐉', label: 'Dragon' },
            { char: '🐲', label: 'Dragon face' },
            { char: '🦂', label: 'Scorpion' },
            { char: '🐜', label: 'Ant' },
            { char: '🐛', label: 'Caterpillar' },
            { char: '🦋', label: 'Butterfly' },
            { char: '🦎', label: 'Lizard' },
            { char: '👻', label: 'Ghost' },
            { char: '👺', label: 'Goblin' },
        ],
    },
    {
        label: 'Places',
        emoji: [
            { char: '🏠', label: 'House' },
            { char: '🏰', label: 'Fortress' },
            { char: '⛺', label: 'Tent' },
            { char: '📜', label: 'Scroll' },
            { char: '🌀', label: 'Portal' },
            { char: '🚧', label: 'Beacon' },
            { char: '🖼', label: 'Painting' },
            { char: '🧭', label: 'Compass' },
            { char: '⚓', label: 'Anchor' },
            { char: '🌊', label: 'Ocean' },
            { char: '🌿', label: 'Plant' },
            { char: '🛏', label: 'Bed' },
            { char: '📦', label: 'Chest' },
            { char: '🏔', label: 'Snow mountain' },
            { char: '⛰', label: 'Mountain' },
            { char: '🌋', label: 'Volcano' },
            { char: '🏕', label: 'Camp' },
            { char: '🏛', label: 'Hall' },
            { char: '🏡', label: 'Farmhouse' },
            { char: '🏚', label: 'Ruin' },
            { char: '🛖', label: 'Hut' },
            { char: '⛵', label: 'Sailboat' },
            { char: '🛶', label: 'Canoe' },
            { char: '🪦', label: 'Gravestone' },
            { char: '⚰', label: 'Coffin' },
            { char: '🗿', label: 'Statue' },
            { char: '🌉', label: 'Bridge' },
            { char: '🚪', label: 'Door' },
            { char: '🪜', label: 'Ladder' },
            { char: '🪑', label: 'Chair' },
            { char: '🪟', label: 'Window' },
            { char: '🗺', label: 'Map' },
            { char: '📍', label: 'Pin' },
            { char: '🚩', label: 'Flag' },
            { char: '🏴', label: 'Black flag' },
            { char: '🪧', label: 'Placard' },
            { char: '⛲', label: 'Fountain' },
            { char: '⛩', label: 'Shrine' },
        ],
    },
    {
        label: 'Signals',
        emoji: [
            { char: '✅', label: 'Check' },
            { char: '❌', label: 'Cross' },
            { char: '❗', label: 'Exclamation' },
            { char: '❓', label: 'Question' },
            { char: '⚠', label: 'Warning' },
            { char: '⭐', label: 'Star' },
            { char: '✨', label: 'Sparkles' },
            { char: '❤', label: 'Red heart' },
            { char: '💚', label: 'Green heart' },
            { char: '💙', label: 'Blue heart' },
            { char: '➡', label: 'Right arrow' },
            { char: '⬅', label: 'Left arrow' },
            { char: '⬆', label: 'Up arrow' },
            { char: '⬇', label: 'Down arrow' },
            { char: '🔔', label: 'Bell' },
            { char: '🔒', label: 'Lock' },
            { char: '🔑', label: 'Key' },
            { char: '💤', label: 'Sleep' },
            { char: '✔', label: 'Check mark' },
            { char: '✖', label: 'Multiply' },
            { char: '☑', label: 'Checked box' },
            { char: '➕', label: 'Plus' },
            { char: '➖', label: 'Minus' },
            { char: '⛔', label: 'No entry' },
            { char: '🚫', label: 'Prohibited' },
            { char: '↔', label: 'Left-right arrow' },
            { char: '↕', label: 'Up-down arrow' },
            { char: '↗', label: 'Up-right arrow' },
            { char: '↘', label: 'Down-right arrow' },
            { char: '↙', label: 'Down-left arrow' },
            { char: '↖', label: 'Up-left arrow' },
            { char: '🔓', label: 'Unlocked' },
            { char: '🔕', label: 'Muted bell' },
            { char: '📢', label: 'Loudspeaker' },
            { char: '💬', label: 'Speech' },
            { char: '💭', label: 'Thought' },
            { char: '💡', label: 'Light bulb' },
            { char: '⏰', label: 'Alarm clock' },
            { char: '⌛', label: 'Hourglass' },
            { char: 'ℹ', label: 'Info' },
            { char: '🎵', label: 'Music note' },
            { char: '🎶', label: 'Music notes' },
        ],
    },
    {
        label: 'Hearts & Shapes',
        emoji: [
            { char: '💛', label: 'Yellow heart' },
            { char: '🧡', label: 'Orange heart' },
            { char: '💜', label: 'Purple heart' },
            { char: '🖤', label: 'Black heart' },
            { char: '🤍', label: 'White heart' },
            { char: '🤎', label: 'Brown heart' },
            { char: '💔', label: 'Broken heart' },
            { char: '⭕', label: 'Hollow circle' },
            { char: '🔴', label: 'Red circle' },
            { char: '🟡', label: 'Yellow circle' },
            { char: '🟢', label: 'Green circle' },
            { char: '🔵', label: 'Blue circle' },
            { char: '🟣', label: 'Purple circle' },
            { char: '⚪', label: 'White circle' },
            { char: '⚫', label: 'Black circle' },
            { char: '🔺', label: 'Red triangle' },
            { char: '🔻', label: 'Down triangle' },
            { char: '🔸', label: 'Small orange diamond' },
            { char: '♦', label: 'Diamond suit' },
            { char: '♠', label: 'Spade suit' },
            { char: '♣', label: 'Club suit' },
            { char: '♥', label: 'Heart suit' },
        ],
    },
    {
        label: 'Sea & Sky',
        emoji: [
            { char: '🐋', label: 'Whale' },
            { char: '🐬', label: 'Dolphin' },
            { char: '🦈', label: 'Shark' },
            { char: '🐙', label: 'Octopus' },
            { char: '🦑', label: 'Squid' },
            { char: '🐡', label: 'Pufferfish' },
            { char: '🦀', label: 'Crab' },
            { char: '🦞', label: 'Lobster' },
            { char: '🦅', label: 'Eagle' },
            { char: '🦆', label: 'Duck' },
            { char: '🦉', label: 'Owl' },
            { char: '🦇', label: 'Bat' },
            { char: '🐓', label: 'Rooster' },
            { char: '🐦', label: 'Bird' },
        ],
    },
    {
        label: 'Nature & Weather',
        emoji: [
            { char: '☀', label: 'Sun' },
            { char: '🌙', label: 'Crescent moon' },
            { char: '🌕', label: 'Full moon' },
            { char: '🌑', label: 'New moon' },
            { char: '🌌', label: 'Night sky' },
            { char: '☄', label: 'Comet' },
            { char: '☁', label: 'Cloud' },
            { char: '🌧', label: 'Rain' },
            { char: '⛈', label: 'Storm' },
            { char: '🌨', label: 'Snowfall' },
            { char: '❄', label: 'Snowflake' },
            { char: '⛄', label: 'Snowman' },
            { char: '🌪', label: 'Tornado' },
            { char: '🌫', label: 'Fog' },
            { char: '🌈', label: 'Rainbow' },
            { char: '🌳', label: 'Tree' },
            { char: '🌴', label: 'Palm' },
            { char: '🌵', label: 'Cactus' },
            { char: '🌱', label: 'Seedling' },
            { char: '🍁', label: 'Maple leaf' },
            { char: '🍂', label: 'Fallen leaves' },
            { char: '🍃', label: 'Wind leaf' },
            { char: '🌸', label: 'Blossom' },
            { char: '🌻', label: 'Sunflower' },
            { char: '🌹', label: 'Rose' },
            { char: '🌍', label: 'World' },
        ],
    },
];
